name: Build Container

on:
  schedule:
    - cron: "2 10 * * *" # Runs daily at 2:10  UTC
  workflow_dispatch:

jobs:
 build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: develop

      - name: Set environment variables
        run: |
          echo "SMING_BRANCH=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          # Get the latest tag or use branch name if no tags available
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          if [ -z "$LATEST_TAG" ]; then
            echo "SMING_TAG=$(git rev-parse --abbrev-ref HEAD)" >> $GITHUB_ENV
          else
            echo "SMING_TAG=$LATEST_TAG" >> $GITHUB_ENV
          fi
      
          - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: |
            pjakobs/sming:latest
            pjakobs/sming:${{ env.SMING_TAG }}
            pjakobs/sming:${{ env.SMING_BRANCH }}
          labels: |
            org.opencontainers.image.title=Sming
            org.opencontainers.image.description=Sming build image for Esp8266, Esp32 and Esp32c3
            org.opencontainers.image.version=${{ env.SMING_TAG }}
            org.opencontainers.image.revision=${{ env.SMING_BRANCH }}
